database:
  driverClass: com.mysql.jdbc.Driver
  user: foodly
  password: foodly
  url: jdbc:mysql://localhost/foodly
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect

  validationQuery: "SELECT 1"
  minSize: 4
  maxSize: 32

  checkConnectionWhileIdle: false

